% function [plane_data, plane_data_new] = get_bonsai_twopframetimes_by_planes(filepath, nplanes)
% % [plane_data] = get_bonsai_twopframetimes_by_planes(filepath, nplanes)
% % Function to read csv file of frame times and split into frametimes per plane.
% 
% 
% % Read CSV file generated by Bonsai containing all the TwoP frame timestamps 
% twop_csv = readtable(filepath);
% 
% % Temp clean up; remove rows where TwoPFrameTime is 0;
% if twop_csv.TwoPFrameTime(1) == 0
%     twop_csv = twop_csv(2:end, :);
% end
% twop_csv.TwoPFrameTime = twop_csv.TwoPFrameTime./1000;
% twop_csv.LastSyncPulseTime = twop_csv.LastSyncPulseTime./1000;
% twop_csv.ArduinoTime = twop_csv.ArduinoTime./1000;
% 
% % Initialize empty tables for each plane's data with the same variable names
% for p = 1:nplanes
%     plane_data.(['plane' num2str(p-1)]) = twop_csv(p:nplanes:end, :); 
%     num_frames_per_plane(p) = size(plane_data.(['plane' num2str(p-1)]),1);
%     plane_data_new{p} = twop_csv(p:nplanes:end, :);
% end


function [plane_data] = get_bonsai_twopframetimes_by_planes(filepath, nplanes)
% Reads CSV file of frame times and splits into frametimes per plane.
% Supports legacy '2P' files and UCL-Open 'MatrixArduino' files.

twop_csv = readtable(filepath, 'VariableNamingRule', 'preserve');
vars = twop_csv.Properties.VariableNames;

if ismember('TwoPFrameTime', vars)
    % legacy format
    timeCol = "TwoPFrameTime";
    syncCol = "LastSyncPulseTime";
    arduinoCol = "ArduinoTime";

    twop_csv.(timeCol) = twop_csv.(timeCol) ./ 1000;
    twop_csv.(syncCol) = twop_csv.(syncCol) ./ 1000;
    twop_csv.(arduinoCol) = twop_csv.(arduinoCol) ./ 1000;

elseif ismember('Value.Last2PFrameTime', vars)
    % UCL-OPEN FORMAT
    timeCol = "Value.Last2PFrameTime";
    syncCol = "Value.LastSyncPulseTime";
    arduinoCol = "Seconds";

    twop_csv.(timeCol) = twop_csv.(timeCol) ./ 1000;
    twop_csv.(syncCol) = twop_csv.(syncCol) ./ 1000;
    % Arduino time does not need to be converted to seconds; already saved
    % here


    %% Remove duplicate 2P frame timestamps @AMAN
    % This removes the entire row (including the extra Seconds/SyncPulse entries)
    % to ensure the clock remains aligned with unique microscope frames.
    % Only keeps the first instance of each unique 2P frame time. New
    % logging is triggered based on ArduinoTime where previous legacy
    % version was tiggered based on TwoPFrameTimes and did not require
    % this additional step.
    [~, uniqueIdx, ~] = unique(twop_csv.(timeCol), 'stable');
    twop_csv = twop_csv(uniqueIdx, :);

else
    error('Could not find 2P frame time columns in file: %s', filepath);
end

% Remove rows where 2P time clock is 0
rows_to_remove = (twop_csv.(timeCol) == 0);
twop_csv(rows_to_remove, :) = [];

% standardising headers
twop_csv.TwoPFrameTime = twop_csv.(timeCol);
twop_csv.ArduinoTime    = twop_csv.(arduinoCol);
twop_csv.LastSyncPulseTime = twop_csv.(syncCol);

%  split by planes
for p = 1:nplanes
    planeName = ['plane' num2str(p-1)];
    plane_data.(planeName) = twop_csv(p:nplanes:end, :);
end
end