% function [plane_data, plane_data_new] = get_bonsai_twopframetimes_by_planes(filepath, nplanes)
% % [plane_data] = get_bonsai_twopframetimes_by_planes(filepath, nplanes)
% % Function to read csv file of frame times and split into frametimes per plane.
% 
% 
% % Read CSV file generated by Bonsai containing all the TwoP frame timestamps 
% twop_csv = readtable(filepath);
% 
% % Temp clean up; remove rows where TwoPFrameTime is 0;
% if twop_csv.TwoPFrameTime(1) == 0
%     twop_csv = twop_csv(2:end, :);
% end
% twop_csv.TwoPFrameTime = twop_csv.TwoPFrameTime./1000;
% twop_csv.LastSyncPulseTime = twop_csv.LastSyncPulseTime./1000;
% twop_csv.ArduinoTime = twop_csv.ArduinoTime./1000;
% 
% % Initialize empty tables for each plane's data with the same variable names
% for p = 1:nplanes
%     plane_data.(['plane' num2str(p-1)]) = twop_csv(p:nplanes:end, :); 
%     num_frames_per_plane(p) = size(plane_data.(['plane' num2str(p-1)]),1);
%     plane_data_new{p} = twop_csv(p:nplanes:end, :);
% end


function [plane_data] = get_bonsai_twopframetimes_by_planes(filepath, nplanes)
% Reads CSV file of frame times and splits into frametimes per plane.
% Supports legacy '2P' files and UCL-Open 'MatrixArduino' files.

% Use 'preserve' to keep dots like 'Value.Last2PFrameTime'
twop_csv = readtable(filepath, 'VariableNamingRule', 'preserve');

% --- DETECT FORMAT AND MAP COLUMNS ---
vars = twop_csv.Properties.VariableNames;

if ismember('TwoPFrameTime', vars)
    % LEGACY FORMAT
    timeCol = "TwoPFrameTime";
    syncCol = "LastSyncPulseTime";
    arduinoCol = "ArduinoTime";
    
    % Convert ms to s for legacy
    twop_csv.(timeCol) = twop_csv.(timeCol) ./ 1000;
    twop_csv.(syncCol) = twop_csv.(syncCol) ./ 1000;
    twop_csv.(arduinoCol) = twop_csv.(arduinoCol) ./ 1000;

elseif ismember('Value.Last2PFrameTime', vars)
    % UCL-OPEN FORMAT
    timeCol = "Value.Last2PFrameTime";
    syncCol = "Value.LastSyncPulseTime";
    arduinoCol = "Seconds"; 
    
    % Convert UCL-Open ms values to seconds
    twop_csv.(timeCol) = twop_csv.(timeCol) ./ 1000;
    twop_csv.(syncCol) = twop_csv.(syncCol) ./ 1000;
    
    % Note: 'Seconds' is typically already in seconds in this format, 
    % so no division is applied to arduinoCol here.
else
    error('Could not find 2P frame time columns in file: %s', filepath);
end

% --- CLEANUP ---
% Remove all rows where the 2P time is 0 (microscope hadn't started yet)
rows_to_remove = (twop_csv.(timeCol) == 0);
twop_csv(rows_to_remove, :) = [];

% --- STANDARDIZE COLUMN NAMES FOR PIPELINE ---
% Standardizing headers so the main merge function remains compatible
twop_csv.TwoPFrameTime = twop_csv.(timeCol);
twop_csv.ArduinoTime    = twop_csv.(arduinoCol);
twop_csv.LastSyncPulseTime = twop_csv.(syncCol);

% --- SPLIT BY PLANE ---
for p = 1:nplanes
    plane_data.(['plane' num2str(p-1)]) = twop_csv(p:nplanes:end, :); 
end
end
